language: node_js
group: edge
sudo: required
services:
  - mongodb
  - redis-server
  - docker
node_js:
  - "0.10"
  - "4.4.3"
before_install:
  - npm install fh-build -g
  - fh-build template
install: npm install
